"""Parent-facing data access router (FERPA §99.10 / COPPA §312.6 B2).

Provides endpoints for verified parents/guardians to view their child's
educational records:
- GET /api/v1/parent/{child_id}/data — JSON with all student records
- GET /api/v1/parent/{child_id}/export — CSV export of student data

Identity verification is done via a token query parameter. For under-13
students, the token is the ``parental_consent_id`` generated during COPPA
registration. For 13+ students (or any student), a
``parent_verification_token`` can be generated by the student via
POST /api/v1/student/{id}/generate-parent-token.

All access is logged to ``parent_access_log`` for audit trail compliance.
"""

from __future__ import annotations

import csv
import io
import logging
from datetime import datetime, timezone
from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, Query, Request, Response, status
from sqlalchemy import select, func as sa_func
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models import (
    User,
    SessionModel,
    Event,
    FeedbackLog,
    SkillState,
    Enrollment,
    ClassModel,
    Sim,
    ParentAccessLog,
)
from app.schemas import (
    ParentDataResponse,
    ParentChildProfile,
    ParentSessionItem,
    ParentEventItem,
    ParentFeedbackItem,
    ParentSkillStateItem,
    ParentEnrollmentItem,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/parent", tags=["parent"])


# ── Helpers ────────────────────────────────────────────────────────────


def _format_dt(dt: datetime | None) -> str:
    """Format datetime as ISO string, or empty string."""
    if dt is None:
        return ""
    return dt.isoformat()


async def _verify_parent_token(
    child_id: str,
    token: str,
    db: AsyncSession,
) -> User:
    """Verify a parent verification token and return the child User.

    The token must match either:
    1. The child's ``parental_consent_id`` (for under-13 COPPA flow)
    2. The child's ``parent_verification_token`` (generated by the student)

    Raises 401 if the token is invalid.
    Raises 404 if the child user does not exist.
    """
    # Fetch the child user
    result = await db.execute(select(User).where(User.id == child_id))
    child = result.scalar_one_or_none()

    if child is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Student not found",
        )

    if child.deleted_at is not None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="This account has been deactivated",
        )

    # Check token against both possible verification fields
    token_valid = False
    if child.parental_consent_id and token == child.parental_consent_id:
        token_valid = True
    if child.parent_verification_token and token == child.parent_verification_token:
        token_valid = True

    if not token_valid:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid verification token. Please check the token and try again.",
        )

    return child


async def _log_parent_access(
    child_id: str,
    token: str,
    action: str,
    request: Request | None,
    db: AsyncSession,
) -> None:
    """Log a parent data access event to the audit trail."""
    ip_address = None
    user_agent = None
    if request:
        ip_address = request.client.host if request.client else None
        user_agent = request.headers.get("user-agent")

    access_log = ParentAccessLog(
        child_id=child_id,
        verification_token=token,
        action=action,
        ip_address=ip_address,
        user_agent=user_agent,
    )
    db.add(access_log)
    await db.flush()
    logger.info(
        "Parent access logged: child=%s action=%s log_id=%s",
        child_id,
        action,
        access_log.id,
    )


# ── GET /api/v1/parent/{child_id}/data ────────────────────────────────


@router.get(
    "/{child_id}/data",
    response_model=ParentDataResponse,
    summary="View child's educational records",
    description="Returns all student records for a verified parent/guardian: "
    "profile, sessions, events, feedback, skill states, and enrollments. "
    "Requires a ?token= query parameter with a valid parent verification token. "
    "FERPA/COPPA compliance endpoint (Finding B2).",
    responses={
        200: {"description": "Complete student records"},
        401: {"description": "Invalid verification token"},
        404: {"description": "Student not found"},
    },
    openapi_extra={
        "security": [],  # No Bearer auth — token-based verification
    },
)
async def parent_get_data(
    child_id: str,
    token: str = Query(..., description="Parent verification token"),
    request: Request = None,
    db: AsyncSession = Depends(get_db),
):
    """Get all student records for a verified parent/guardian.

    Returns a comprehensive view of the child's educational data
    including profile, sessions, events, AI feedback, skill mastery
    states, and class enrollments.
    """
    # Verify the parent token
    child = await _verify_parent_token(child_id, token, db)

    # ── Fetch profile data ──
    profile = ParentChildProfile(
        id=child.id,
        email=child.email,
        username=child.username,
        display_name=child.display_name,
        role=child.role,
        account_status=child.account_status,
        created_at=child.created_at,
        last_active_at=child.last_active_at,
    )

    # ── Fetch sessions (most recent 50) ──
    session_result = await db.execute(
        select(SessionModel)
        .where(SessionModel.student_id == child_id)
        .order_by(SessionModel.started_at.desc())
        .limit(50)
    )
    sessions_raw = session_result.scalars().all()

    sessions: list[ParentSessionItem] = []
    for s in sessions_raw:
        sim_slug = None
        sim_title = None
        if s.sim:
            sim_slug = s.sim.slug
            sim_title = s.sim.title_en
        sessions.append(
            ParentSessionItem(
                id=s.id,
                sim_id=s.sim_id,
                sim_slug=sim_slug,
                sim_title=sim_title,
                task_slug=s.task_slug,
                page_type=s.page_type,
                started_at=s.started_at,
                ended_at=s.ended_at,
                duration_seconds=s.duration_seconds,
                is_completed=s.is_completed,
            )
        )

    # ── Fetch events (most recent 200) ──
    event_result = await db.execute(
        select(Event)
        .where(Event.student_id == child_id)
        .order_by(Event.server_ts.desc())
        .limit(200)
    )
    events_raw = event_result.scalars().all()
    events = [
        ParentEventItem(
            id=e.id,
            event_type=e.event_type,
            event_name=e.event_name,
            event_value=e.event_value,
            client_ts=e.client_ts,
            server_ts=e.server_ts,
        )
        for e in events_raw
    ]

    # ── Fetch feedback logs ──
    feedback_result = await db.execute(
        select(FeedbackLog)
        .where(FeedbackLog.student_id == child_id)
        .order_by(FeedbackLog.created_at.desc())
        .limit(100)
    )
    feedback_raw = feedback_result.scalars().all()
    feedback = [
        ParentFeedbackItem(
            id=f.id,
            feedback_type=f.feedback_type,
            feedback_text=f.feedback_text,
            source=f.source,
            was_helpful=f.was_helpful,
            created_at=f.created_at,
        )
        for f in feedback_raw
    ]

    # ── Fetch skill states ──
    skill_result = await db.execute(
        select(SkillState).where(SkillState.student_id == child_id)
    )
    skill_raw = skill_result.scalars().all()
    skill_states = [
        ParentSkillStateItem(
            skill_id=s.skill_id,
            probability=float(s.probability),
            total_attempts=s.total_attempts,
            correct_attempts=s.correct_attempts,
            last_practiced=s.last_practiced,
        )
        for s in skill_raw
    ]

    # ── Fetch enrollments ──
    enrollment_result = await db.execute(
        select(Enrollment)
        .where(Enrollment.student_id == child_id)
    )
    enrollment_raw = enrollment_result.scalars().all()
    enrollments: list[ParentEnrollmentItem] = []
    for enr in enrollment_raw:
        class_name = None
        if enr.class_:
            class_name = enr.class_.name
        enrollments.append(
            ParentEnrollmentItem(
                class_id=enr.class_id,
                class_name=class_name,
                enrolled_at=enr.enrolled_at,
            )
        )

    # ── Aggregate counts ──
    total_sessions = len(sessions_raw)
    total_events = len(events_raw)
    total_feedback = len(feedback_raw)
    total_skills = len(skill_raw)

    # Audit log
    await _log_parent_access(child_id, token, "view_data", request, db)

    return ParentDataResponse(
        profile=profile,
        sessions=sessions,
        events=events,
        feedback=feedback,
        skill_states=skill_states,
        enrollments=enrollments,
        total_sessions=total_sessions,
        total_events=total_events,
        total_feedback=total_feedback,
        total_skills=total_skills,
    )


# ── GET /api/v1/parent/{child_id}/export ──────────────────────────────


@router.get(
    "/{child_id}/export",
    summary="Export child's data as CSV",
    description="Download a CSV file of the child's session data for a "
    "verified parent/guardian. Requires a ?token= query parameter with "
    "a valid parent verification token. "
    "FERPA/COPPA compliance endpoint (Finding B2).",
    responses={
        200: {
            "content": {"text/csv": {}},
            "description": "CSV file with child's session data",
        },
        401: {"description": "Invalid verification token"},
        404: {"description": "Student not found"},
    },
    openapi_extra={
        "security": [],  # No Bearer auth — token-based verification
    },
)
async def parent_export_csv(
    child_id: str,
    token: str = Query(..., description="Parent verification token"),
    request: Request = None,
    db: AsyncSession = Depends(get_db),
):
    """Export child's session data as CSV.

    Returns a CSV file with one row per session, including session
    metadata, sim details, duration, completion status, and feedback count.
    """
    # Verify the parent token
    child = await _verify_parent_token(child_id, token, db)

    # Fetch sessions with related data
    session_result = await db.execute(
        select(SessionModel)
        .where(SessionModel.student_id == child_id)
        .order_by(SessionModel.started_at.desc())
    )
    sessions_raw = session_result.scalars().all()

    rows: list[dict] = []
    for s in sessions_raw:
        sim_slug = ""
        sim_title = ""
        if s.sim:
            sim_slug = s.sim.slug
            sim_title = s.sim.title_en

        # Event count for this session
        event_count = (
            await db.execute(
                select(sa_func.count(Event.id)).where(
                    Event.session_id == s.id
                )
            )
        ).scalar() or 0

        # Feedback count for this session
        feedback_count = (
            await db.execute(
                select(sa_func.count(FeedbackLog.id)).where(
                    FeedbackLog.session_id == s.id
                )
            )
        ).scalar() or 0

        rows.append(
            {
                "session_id": s.id,
                "sim_slug": sim_slug,
                "sim_title": sim_title,
                "task_slug": s.task_slug or "",
                "page_type": s.page_type,
                "started_at": _format_dt(s.started_at),
                "ended_at": _format_dt(s.ended_at),
                "duration_seconds": s.duration_seconds or "",
                "is_completed": s.is_completed,
                "event_count": event_count,
                "feedback_count": feedback_count,
            }
        )

    # Build CSV
    output = io.StringIO()
    fieldnames = [
        "session_id", "sim_slug", "sim_title", "task_slug", "page_type",
        "started_at", "ended_at", "duration_seconds", "is_completed",
        "event_count", "feedback_count",
    ]
    writer = csv.DictWriter(output, fieldnames=fieldnames, extrasaction="ignore")
    writer.writeheader()
    writer.writerows(rows)
    csv_content = output.getvalue()

    # Audit log
    await _log_parent_access(child_id, token, "export_csv", request, db)

    return Response(
        content=csv_content,
        media_type="text/csv; charset=utf-8",
        headers={
            "Content-Disposition": (
                f'attachment; filename="student_{child_id}_export.csv"'
            ),
        },
    )
